import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const defaultRolloutOrigin = "https://fudge-design-md-rollout.simdi.workers.dev";
const defaultFudgeOrigin = "https://design.withfudge.com";

export async function readCollection(root) {
  const guideDir = resolve(root, "design-md");
  const guideDomains = new Set(
    (await readdir(guideDir))
      .filter((file) => file.endsWith(".md"))
      .map((file) => basename(file, ".md")),
  );
  const readme = await readFile(resolve(root, "README.md"), "utf8");
  return {
    guideDomains,
    readmeEntries: matches(readme, /^### /gm),
    representativeImages: matches(readme, /^\[!\[How /gm),
    guideLinks: matches(readme, /^\[Open guide\]/gm),
  };
}

export function buildStatusSnapshot({
  collection,
  rolloutHealth,
  rolloutProgress,
  acceptedManifest,
  domainSitemapXml,
  snapshotAt,
}) {
  const cloudAccepted = new Set(acceptedManifest?.domains ?? []);
  const sitemapDomains = domainSitemapDomains(domainSitemapXml);
  const missingCloudGuides = difference(cloudAccepted, collection.guideDomains);
  const sitemapOnly = difference(sitemapDomains, collection.guideDomains);
  const mirrorOnly = difference(collection.guideDomains, sitemapDomains);
  const publicGuideCount = collection.guideDomains.size;
  const cloudAcceptedInMirror = publicGuideCount - difference(
    collection.guideDomains,
    cloudAccepted,
  ).length;

  if (
    collection.readmeEntries !== publicGuideCount
    || collection.representativeImages !== publicGuideCount
    || collection.guideLinks !== publicGuideCount
  ) {
    throw new Error("README index does not match the public guide collection");
  }
  if (missingCloudGuides.length > 0) {
    throw new Error(
      `${missingCloudGuides.length} Cloudflare-accepted guides are missing from the public mirror`,
    );
  }

  return {
    schemaVersion: 2,
    snapshotAt,
    collection: {
      publicGuides: publicGuideCount,
      readmeEntries: collection.readmeEntries,
      representativeImages: collection.representativeImages,
      guideLinks: collection.guideLinks,
      cloudAccepted: cloudAccepted.size,
      cloudAcceptedInMirror,
      retainedPreCloudflare: publicGuideCount - cloudAcceptedInMirror,
    },
    reconciliation: {
      domainSitemapGuides: sitemapDomains.size,
      sitemapOnly,
      mirrorOnly,
      aligned: sitemapOnly.length === 0 && mirrorOnly.length === 0,
    },
    rollout: {
      serviceState: rolloutHealth?.state ?? "unknown",
      dispatch: rolloutHealth?.dispatch ?? "unknown",
      publishing: rolloutHealth?.publishing === true,
      counts: rolloutProgress?.counts ?? {},
      terminal: rolloutProgress?.terminal ?? null,
      completionPercent: rolloutProgress?.completionPercent ?? null,
      updatedAt: rolloutProgress?.updatedAt ?? null,
      lastCompletedAt: rolloutProgress?.lastCompletedAt ?? null,
      blockedReasons: rolloutProgress?.blockedReasons ?? [],
    },
    localSupervisor: {
      state: "retired",
      replacedBy: "Cloudflare Workflows",
    },
    historicalDomainRecords: {
      state: "historical",
      path: "status/domains",
    },
  };
}

export function renderStatusMarkdown(snapshot) {
  const { collection, reconciliation, rollout } = snapshot;
  const counts = rollout.counts;
  const mismatch = reconciliation.aligned
    ? "- sitemap and GitHub mirror: aligned"
    : [
        `- sitemap-only guides: ${reconciliation.sitemapOnly.length}`,
        `- mirror-only guides: ${reconciliation.mirrorOnly.length}`,
      ].join("\n");
  return [
    "# DESIGN.md collection status",
    "",
    "Generated by `scripts/status.mjs` from the public guide tree, README, live",
    "domain sitemap, and Cloudflare rollout aggregate. Do not edit by hand.",
    "",
    "## Public collection",
    "",
    `- accepted GitHub guides: ${collection.publicGuides}`,
    `- README guide entries: ${collection.readmeEntries}`,
    `- representative README images: ${collection.representativeImages}`,
    `- Cloudflare-rollout guides in the mirror: ${collection.cloudAcceptedInMirror}`,
    `- valid guides retained from before the Cloudflare rollout: ${collection.retainedPreCloudflare}`,
    `- domain-sitemap guides: ${reconciliation.domainSitemapGuides}`,
    mismatch,
    "",
    "## Cloudflare rollout",
    "",
    `- service: ${rollout.serviceState}`,
    `- dispatch: ${rollout.dispatch}`,
    `- publishing: ${rollout.publishing ? "enabled" : "paused"}`,
    `- queued: ${counts.queued ?? 0}`,
    `- running: ${counts.running ?? 0}`,
    `- published: ${counts.published ?? 0}`,
    `- blocked: ${counts.blocked ?? 0}`,
    `- total jobs: ${counts.total ?? rollout.terminal ?? 0}`,
    `- completion: ${rollout.completionPercent ?? 0}%`,
    `- rollout updated: ${rollout.updatedAt ?? "unavailable"}`,
    `- last completed: ${rollout.lastCompletedAt ?? "unavailable"}`,
    "",
    "[Open the live aggregate](https://fudge-design-md-rollout.simdi.workers.dev/v1/progress).",
    "",
    "## Local supervisor",
    "",
    "The local supervisor is retired. Cloudflare Workflows owns rollout execution.",
    "The records under `status/domains/` are historical migration detail, not an",
    "active queue or current worker heartbeat.",
    "",
    `Snapshot generated: ${snapshot.snapshotAt}`,
    "",
  ].join("\n");
}

export async function updateStatus({
  root,
  rolloutHealth,
  rolloutProgress,
  acceptedManifest,
  domainSitemapXml,
  snapshotAt = new Date().toISOString(),
}) {
  const collection = await readCollection(root);
  let snapshot = buildStatusSnapshot({
    collection,
    rolloutHealth,
    rolloutProgress,
    acceptedManifest,
    domainSitemapXml,
    snapshotAt,
  });
  const statusDir = resolve(root, "status");
  await mkdir(statusDir, { recursive: true });
  try {
    const previous = JSON.parse(await readFile(resolve(statusDir, "index.json"), "utf8"));
    if (sameSnapshot(previous, snapshot) && typeof previous.snapshotAt === "string") {
      snapshot = { ...snapshot, snapshotAt: previous.snapshotAt };
    }
  } catch {}
  await Promise.all([
    writeFile(resolve(statusDir, "index.json"), `${JSON.stringify(snapshot, null, 2)}\n`),
    writeFile(resolve(statusDir, "STATUS.md"), renderStatusMarkdown(snapshot)),
    writeFile(resolve(statusDir, "supervisor.json"), `${JSON.stringify({
      schemaVersion: 2,
      state: "retired",
      replacedBy: "Cloudflare Workflows",
      snapshotAt: snapshot.snapshotAt,
    }, null, 2)}\n`),
  ]);
  return snapshot;
}

async function main() {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const rolloutOrigin = process.env.FUDGE_ROLLOUT_ORIGIN ?? defaultRolloutOrigin;
  const fudgeOrigin = process.env.FUDGE_ORIGIN ?? defaultFudgeOrigin;
  const [rolloutHealth, rolloutProgress, acceptedManifest, domainSitemapXml] = await Promise.all([
    fetchJson(`${rolloutOrigin}/health`),
    fetchJson(`${rolloutOrigin}/v1/progress`),
    fetchJson(`${rolloutOrigin}/v1/accepted`),
    fetchText(`${fudgeOrigin}/sitemaps/domains.xml`),
  ]);
  const snapshot = await updateStatus({
    root,
    rolloutHealth,
    rolloutProgress,
    acceptedManifest,
    domainSitemapXml,
  });
  process.stdout.write(`${JSON.stringify({
    status: "updated",
    publicGuides: snapshot.collection.publicGuides,
    cloudAccepted: snapshot.collection.cloudAccepted,
    domainSitemapGuides: snapshot.reconciliation.domainSitemapGuides,
    aligned: snapshot.reconciliation.aligned,
  })}\n`);
}

async function fetchJson(url) {
  const response = await fetch(url, { headers: { "user-agent": "fudge-design-md-status/1.0" } });
  if (!response.ok) throw new Error(`Could not fetch ${url}: ${response.status}`);
  return response.json();
}

async function fetchText(url) {
  const response = await fetch(url, { headers: { "user-agent": "fudge-design-md-status/1.0" } });
  if (!response.ok) throw new Error(`Could not fetch ${url}: ${response.status}`);
  return response.text();
}

function domainSitemapDomains(xml) {
  const domains = new Set();
  for (const match of xml.matchAll(/<loc>[^<]+\/share\/([^/<]+)-design<\/loc>/g)) {
    domains.add(decodeURIComponent(match[1]));
  }
  return domains;
}

function difference(left, right) {
  return [...left].filter((value) => !right.has(value)).sort((a, b) => a.localeCompare(b));
}

function matches(value, pattern) {
  return [...value.matchAll(pattern)].length;
}

function sameSnapshot(left, right) {
  const withoutTime = ({ snapshotAt: _snapshotAt, ...value }) => value;
  return JSON.stringify(withoutTime(left)) === JSON.stringify(withoutTime(right));
}

if (
  process.argv[1]
  && import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  await main();
}
